services:
  affine:
    image: trackwork-local:dev
    build:
      context: ../..
      dockerfile: .github/deployment/node/Dockerfile
      args:
        GIT_COMMIT: ${GIT_COMMIT:-000000000}
  affine_migration:
    image: trackwork-local:dev

  postgres:
    ports:
      - '127.0.0.1:5432:5432'

  redis:
    ports:
      - '127.0.0.1:6379:6379'
